
spark:
  streaming_app_name: SparkAnalyticsFirmwareDev
  master: local[4]
  batch_interval_millis: 20000 # 10 secs
  window_size_millis: 60000 # 1 minute
  checkpoint_directory: "/tmp/spark-checkpoint"


kinesis:
  stream_name: sense_sensors_data_fanout_one
  endpoint: https://kinesis.us-east-1.amazonaws.com
  app_name: SparkAnalyticsFirmwareConsumerDevKSG
  region: us-east-1

dynamodb:
  region: us-east-1
  endpoint: http://dynamodb.us-east-1.amazonaws.com
  table_name: dev_spark_analytics_firmware
